title: Samuel Coskey
email: scoskey@gmail.com
github_username: scoskey
description: >
  Jump right in and discover...
url: "https://scoskey.org"
baseurl: ""
permalink: /:categories/:title/
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
excerpt_separator: <!--more-->

# main menu
header_pages:
  - courses.md
  - publications.md
  - presentations.md
  - students.md
  - vitae.md

defaults: 
  - scope: 
      path: ""
      type: "posts"
    values:
      layout: mypost
