title: Samuel Coskey
email: scoskey@gmail.com
github_username: scoskey
description: >
  Department of Mathematics, Boise State University, 1910 University Dr,
  Boise, ID 83725-1555.
url: "https://scoskey.github.io"
baseurl: ""
permalink: /:title
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
excerpt_separator: <!--more-->

# main menu
header_pages:
  - courses.md
  - publications.md
  - presentations.md
  - students.md
  - vitae.md

# custom vars
slides_base: http://math.boisestate.edu/~scoskey/slides
docs_base: http://math.boisestate.edu/~scoskey/docs
img_base: http://math.boisestate.edu/~scoskey/img
