title: Samuel Coskey
email: scoskey@nylogic.org
description: > # this means to ignore newlines until "baseurl:"
  Department of Mathematics, Boise State University, 1910 University Dr,
  Boise, ID 83725-1555.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://scoskey.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  scoskey

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock

# Sam config
excerpt_separator: <!--more-->
permalink: /:title
header_pages:
  - courses.md
  - publications.md
  - presentations.md
  - students.md
  - vitae.md

# custom vars
slides_base: http://math.boisestate.edu/~scoskey/slides
docs_base: http://math.boisestate.edu/~scoskey/docs
img_base: http://math.boisestate.edu/~scoskey/img
